### ISSUE TITLE
[gen1] RuntimeError on interrupt

### ISSUE THREAD

**Issue by V3ntus** [darvester/darvester#64]
**Describe the bug**
```py
Initializing 100%|███████████████████████████████████████████████████████████████████████████| 4/4 [00:30<00:00, 0.13/s]
Guilds   5%|███▎                                                                    |  1/22 [00:28<09:39, 0.04 guilds/s]Traceback (most recent call last):
  File "C:\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002673EE5E560>
Traceback (most recent call last):
  File "C:\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002673EE5E560>
Traceback (most recent call last):
  File "C:\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
  File "C:\Python310\lib\asyncio\proactor_events.py", line 108, in close
  File "C:\Python310\lib\asyncio\base_events.py", line 750, in call_soon
  File "C:\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
RuntimeError: Event loop is closed
```

**To Reproduce**
Ctrl+C while running in harvest loop, not on delay

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Version [e.g. 22] Python 3.10

**Additional context**

**Comment by contusionglory** [comment]
```python
asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
try:
    asyncio.run(processToRun())
except KeyboardInterrupt:
    pass
```
running it with this should fix it

**Comment by V3ntus** [comment]
@contusionglory can you describe what this proposal does exactly?

**Comment by contusionglory** [comment]
If the program use asyncio to start the loop setting the asyncio.WindowsSelectorEventLoopPolicy() make the program not printing error on ctrl-c on windows(also it catch keyboard interrupt error), i don't know if the program start in this way but with another asyncio program i made this fixed the error

**Comment by V3ntus** [comment]
Seems this policy is targeted to the Windows platform only. Even then, the default for Unix is `SelectorEventLoop`

**Comment by contusionglory** [comment]
This is an error that only on windows happen for what i know, so it just need an if to check the system version and if it is windows set the policy

**Comment by V3ntus** [comment]
There's a lack of debug information here as well. This issue requires more details before a fix should be implemented
